### ISSUE TITLE
nb plugin install 安装失败

### ISSUE THREAD

**Issue by 1529960009** [EtherLeaF/nonebot-plugin-colab-novelai#2]
![QQ截图20221113111858](https://user-images.githubusercontent.com/45947734/201504075-98ca701e-0057-440d-8299-e3699a5658c1.png)

**Comment by thetapilla** [comment]
插件暂时还没有更新到nonebot商店，请使用```pip install nonebot_plugin_colab_novelai -i https://pypi.python.org/simple```拉取后手动加载插件

**Comment by thetapilla** [comment]
插件已发布至商店
