### ISSUE TITLE
请问如何调整steps等参数？

### ISSUE THREAD

**Issue by NSQX13579** [EtherLeaF/nonebot-plugin-colab-novelai#3]
是直接在tag里描述吗？如果不能调整可否添加此功能？
如steps为-t xxx，cfg为-c xxx，ntags为-g xxx

**Comment by thetapilla** [comment]
这个功能实际上已经写完了 之前偷懒只保留了精简的功能（
目前正在测试这段代码，预计明早打包更新。

**Comment by thetapilla** [comment]
插件[v0.2.1](https://pypi.org/project/nonebot-plugin-colab-novelai/0.2.1/)已更新
