### ISSUE TITLE
安装以后提示unknown error: cannot find Chrome binary怎么解决呢

### ISSUE THREAD

**Issue by 63248797** [EtherLeaF/nonebot-plugin-colab-novelai#6]
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        (No symbol) [0x013DF243]
        (No symbol) [0x01367FD1]
        (No symbol) [0x0125D04D]
        (No symbol) [0x0127A063]
        (No symbol) [0x012782E9]
        (No symbol) [0x012AF056]
        (No symbol) [0x012AEB2A]
        (No symbol) [0x012A8386]
        (No symbol) [0x0128163C]
        (No symbol) [0x0128269D]
        GetHandleVerifier [0x01679A22+2655074]
        GetHandleVerifier [0x0166CA24+2601828]
        GetHandleVerifier [0x01488C0A+619850]
        GetHandleVerifier [0x01487830+614768]
        (No symbol) [0x013705FC]
        (No symbol) [0x01375968]
        (No symbol) [0x01375A55]
        (No symbol) [0x0138051B]
        BaseThreadInitThunk [0x74F96A14+36]
        RtlInitializeExceptionChain [0x76FDA9EF+143]
        RtlInitializeExceptionChain [0x76FDA9BA+90]

**Comment by thetapilla** [comment]
你需要先在服务器上安装Chrome浏览器本体。
